name: ytmusicapi_dart
description: Unofficial API client for YouTube Music. Inspired by sigma67's ytmusicapi for Python.
version: 2.2.3
repository: https://github.com/encrystudio/ytmusicapi_dart
homepage: https://encrystudio.github.io/ytmusicapi_dart

environment:
  sdk: ^3.7.2

dev_dependencies:
  curl_dio_logger_interceptor: ^0.0.2
  lint: ^2.8.0
  lints: ^6.0.0
  test: ^1.24.0

dependencies:
  crypto: ^3.0.6
  dio: ^5.9.0
  dio_http2_adapter: ^2.6.0
  intl: ^0.20.2
  open_url: ^2.0.1
  unorm_dart: ^0.3.2

topics:
  - api
  - cross-platform
  - client
  - youtube-api
  - youtube

false_secrets: 
  - /lib/constants.dart
