name: ytmusicapi_dart
description: Unofficial API client for YouTube Music. Inspired by sigma67's ytmusicapi for Python.
version: 1.0.2
repository: https://github.com/encrystudio/ytmusicapi_dart

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  dio: ^5.8.0+1
  intl: ^0.20.2
